baseURL = "https://www.suojattukoti.fi"
languageCode = "fi"
title = "Suojattu Koti"
theme = "ananke"
pluralizelisttitles = false
summaryLength = 15

logo = "logo.png"

MetaDataFormat = "yaml"
DefaultContentLanguage = "fi"
SectionPagesMenu = "main"
Paginate = 10 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  favicon = "logo.png"
  description = "Sivuiltamme löydät itsellesi ja perheellesi hälytysjärjestelmän kotiisi!"
  facebook = "https://www.facebook.com/Suojattukotifi-108119400703801/"
  twitter = "https://twitter.com/suojattukoti"
  instagram = "#"
  youtube = ""
  github = ""
  gitlab = ""
  linkedin = ""
  mastodon = ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-navy"
  featured_image = "/family.jpg"
  recent_posts_number = 5

  pageNotFoundTitle = "404 - Sivua ei löytynyt"

  [menu]
  [[menu.main]]
    name = "Koti"
    url = "/"
    weight = 1


  [taxonomies]
  tag = "tags"

[permalinks]
  halytysjarjestelma = "/:filename/"

